### ISSUE TITLE
Criar Artefato Gof Estrutural - Facade

### ISSUE THREAD

**Issue by VasconcelosJoao** [UnBArqDsw2024-1/2024.1_G3_My_gov#33]
### Summary

O padrão de projeto Facade é uma solução de design estrutural que fornece uma interface simplificada para um conjunto de interfaces em um subsistema, facilitando a interação com sistemas complexos. Ele atua como um intermediário, ocultando a complexidade do sistema subjacente e oferecendo uma interface mais fácil de usar para os clientes. Este padrão é amplamente utilizado em desenvolvimento de software para melhorar a legibilidade e a manutenção do código.

### Motivation

- **Simplicidade de Uso**: O padrão Facade simplifica a interação com subsistemas complexos, permitindo que os desenvolvedores acessem funcionalidades sem se preocupar com a complexidade interna.
  
- **Desacoplamento**: Ao fornecer uma interface única, o Facade reduz o acoplamento entre o cliente e o subsistema, facilitando a manutenção e a evolução do código.

- **Facilitação de Testes**: Com uma interface simplificada, o Facade torna mais fácil testar o sistema, pois os desenvolvedores podem focar em interações específicas sem se perder na complexidade do subsistema.

- **Melhoria da Legibilidade**: O uso do padrão Facade melhora a legibilidade do código, tornando-o mais intuitivo e acessível, especialmente para novos desenvolvedores que precisam entender rapidamente como interagir com o sistema.

### Aplicações Comuns

- **Integração de Sistemas**: O Facade é frequentemente utilizado para integrar diferentes sistemas ou bibliotecas, fornecendo uma interface unificada que oculta as complexidades de cada sistema.

- **Frameworks e APIs**: Muitos frameworks e APIs utilizam o padrão Facade para simplificar a interação com suas funcionalidades, permitindo que os desenvolvedores utilizem recursos avançados sem uma curva de aprendizado acentuada.

- **Sistemas Legados**: Ao trabalhar com sistemas legados, o padrão Facade pode ser implementado para criar uma nova interface que facilite a interação com o sistema antigo, sem a necessidade de modificar o código existente.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by renannOgomes** [comment]
PR criado
