### ISSUE TITLE
Criar Artefato Gof Criacional - factory

### ISSUE THREAD

**Issue by VasconcelosJoao** [UnBArqDsw2024-1/2024.1_G3_My_gov#34]
### Summary

O padrão de projeto Factory Method é um padrão criacional que fornece uma interface para a criação de objetos em uma superclasse, permitindo que as subclasses decidam quais classes concretas devem ser instanciadas. Este padrão promove a desacoplagem entre o código que utiliza os objetos e o processo de criação, facilitando a extensibilidade e a manutenção do software.

### Motivation

- **Desacoplamento**: O Factory Method permite que o código cliente não precise conhecer a classe concreta dos objetos que está criando, promovendo uma separação clara entre a criação de objetos e seu uso.

- **Flexibilidade**: Ao permitir que subclasses alterem o tipo de objetos criados, o padrão proporciona flexibilidade na adição de novas classes sem modificar o código existente, facilitando a introdução de novas funcionalidades.

- **Centralização da Lógica de Criação**: A lógica de criação de objetos é centralizada em um único local (a fábrica), o que simplifica a gestão de instâncias e reduz a complexidade do código cliente.

- **Facilidade de Testes**: Com a criação de objetos encapsulada, é mais fácil substituir implementações concretas por mocks ou stubs durante os testes, melhorando a testabilidade do código.

### Estrutura do Padrão

O padrão Factory Method é composto pelos seguintes elementos principais:

1. **Produto**: Uma interface ou classe abstrata que define os métodos que todos os produtos concretos devem implementar.

2. **Produtos Concretos**: Classes que implementam a interface do Produto, representando as instâncias específicas que podem ser criadas.

3. **Criador**: Uma classe abstrata que declara o método de criação (Factory Method). Essa classe pode definir uma implementação padrão que pode ser sobrescrita pelas subclasses.

4. **Criadores Concretos**: Subclasses do Criador que implementam o método de criação, retornando uma instância do Produto específico.

### Aplicações Comuns

- **Frameworks e Bibliotecas**: O padrão é frequentemente utilizado em frameworks e bibliotecas onde a criação de objetos deve ser flexível e extensível, permitindo que os desenvolvedores forneçam suas próprias implementações.

- **Sistemas de Plugins**: Em sistemas que suportam plugins, o Factory Method pode ser usado para instanciar diferentes tipos de plugins sem que o sistema principal precise conhecer suas implementações.

- **Desenvolvimento de Jogos**: Em jogos, o padrão pode ser utilizado para criar diferentes tipos de personagens ou itens, permitindo que novas classes sejam adicionadas sem modificar a lógica existente.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NyndoND** [comment]
PR criado
